sh: None: command not found
INFO: Compiled ParcelsRandom ==> /jobfs/25890148.gadi-pbs/parcels-12904/libparcels_random_f9957e45-23a6-44f5-a339-f3b09e649d22.so
Starting plx_hist_165_v1.
plx_hist_165_v1: calculating year 2006...(0/6)
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/plx_sources.py", line 73, in <module>
    plx_source_transit(args.lon, args.exp, v=1, r_range=[0, 2])
  File "/g/data/e14/as3189/OFAM/scripts/plx_sources.py", line 48, in plx_source_transit
    dx = filter_by_year(ds, t)
  File "/g/data/e14/as3189/OFAM/scripts/main.py", line 392, in filter_by_year
    dx = ds.isel(traj=ind_t, obs=ind_o)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/xarray/core/dataset.py", line 2230, in isel
    var_value = var_value.isel(var_indexers)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/xarray/core/variable.py", line 1135, in isel
    return self[key]
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/xarray/core/variable.py", line 780, in __getitem__
    data = as_indexable(self._data)[indexer]
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/xarray/core/indexing.py", line 1312, in __getitem__
    return array[key]
numpy.core._exceptions.MemoryError: Unable to allocate 250. GiB for an array with shape (183308, 183308) and data type float64
